#!/usr/bin/osascript -l JavaScript
ObjC.import('stdlib')

// Build the normal argv/argc
// https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Shell-and-CLI-Interactions#arguments
var args = $.NSProcessInfo.processInfo.arguments
var argv = []
for (var i = 0; i < args.count; i++) {
    argv.push( ObjC.unwrap( args.objectAtIndex(i) ) )
}

if (args.count < 5) {
    console.log("filepath parameter is not found...")
    $.exit(1)
}
var file_path = argv[4]

// Activate Stickies.app & Open 'Import Text…' prompt
// https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/System-Events#clicking-menu-items
var st = Application('Stickies')
st.activate()
var se = Application('System Events')
var proc = se.processes.byName('Stickies');
var openFile = proc.menuBars[0].menuBarItems.byName('File').menus[0].menuItems.byName('Import Text…')
openFile.click()

// Select inputed filepath
// https://stackoverflow.com/a/58144779
// https://eastmanreference.com/complete-list-of-applescript-key-codes
se.keystroke('g', { using: ['command down', 'shift down'] })
delay(0.3)
se.keyCode(51) // delete key
delay(1)
se.keystroke(file_path)
delay(1)
se.keyCode(36) // return key
delay(1)
se.keyCode(36) // return key
